mkdir topic_messages
ros2 topic echo /behavior_tree_log >> /topic_messages/_behavior_tree_log.txt &
ros2 topic echo /bond >> /topic_messages/_bond.txt &
ros2 topic echo /bt_navigator/transition_event >> /topic_messages/_bt_navigator_transition_event.txt &
ros2 topic echo /clicked_point >> /topic_messages/_clicked_point.txt &
ros2 topic echo /clock >> /topic_messages/_clock.txt &
ros2 topic echo /cmd_vel >> /topic_messages/_cmd_vel.txt &
ros2 topic echo /controller_server/transition_event >> /topic_messages/_controller_server_transition_event.txt &
ros2 topic echo /cost_cloud >> /topic_messages/_cost_cloud.txt &
ros2 topic echo /downsampled_costmap >> /topic_messages/_downsampled_costmap.txt &
ros2 topic echo /downsampled_costmap_updates >> /topic_messages/_downsampled_costmap_updates.txt &
ros2 topic echo /evaluation >> /topic_messages/_evaluation.txt &
ros2 topic echo /global_costmap/costmap >> /topic_messages/_global_costmap_costmap.txt &
ros2 topic echo /global_costmap/costmap_raw >> /topic_messages/_global_costmap_costmap_raw.txt &
ros2 topic echo /global_costmap/costmap_updates >> /topic_messages/_global_costmap_costmap_updates.txt &
ros2 topic echo /global_costmap/footprint >> /topic_messages/_global_costmap_footprint.txt &
ros2 topic echo /global_costmap/global_costmap/transition_event >> /topic_messages/_global_costmap_global_costmap_transition_event.txt &
ros2 topic echo /global_costmap/published_footprint >> /topic_messages/_global_costmap_published_footprint.txt &
ros2 topic echo /global_costmap/voxel_marked_cloud >> /topic_messages/_global_costmap_voxel_marked_cloud.txt &
ros2 topic echo /goal_pose >> /topic_messages/_goal_pose.txt &
ros2 topic echo /imu >> /topic_messages/_imu.txt &
ros2 topic echo /initialpose >> /topic_messages/_initialpose.txt &
ros2 topic echo /intel_realsense_r200_depth/camera_info >> /topic_messages/_intel_realsense_r200_depth_camera_info.txt &
ros2 topic echo /intel_realsense_r200_depth/depth/camera_info >> /topic_messages/_intel_realsense_r200_depth_depth_camera_info.txt &
ros2 topic echo /intel_realsense_r200_depth/depth/image_raw >> /topic_messages/_intel_realsense_r200_depth_depth_image_raw.txt &
ros2 topic echo /intel_realsense_r200_depth/image_raw >> /topic_messages/_intel_realsense_r200_depth_image_raw.txt &
ros2 topic echo /intel_realsense_r200_depth/points >> /topic_messages/_intel_realsense_r200_depth_points.txt &
ros2 topic echo /joint_states >> /topic_messages/_joint_states.txt &
ros2 topic echo /local_costmap/clearing_endpoints >> /topic_messages/_local_costmap_clearing_endpoints.txt &
ros2 topic echo /local_costmap/costmap >> /topic_messages/_local_costmap_costmap.txt &
ros2 topic echo /local_costmap/costmap_raw >> /topic_messages/_local_costmap_costmap_raw.txt &
ros2 topic echo /local_costmap/costmap_updates >> /topic_messages/_local_costmap_costmap_updates.txt &
ros2 topic echo /local_costmap/footprint >> /topic_messages/_local_costmap_footprint.txt &
ros2 topic echo /local_costmap/local_costmap/transition_event >> /topic_messages/_local_costmap_local_costmap_transition_event.txt &
ros2 topic echo /local_costmap/published_footprint >> /topic_messages/_local_costmap_published_footprint.txt &
ros2 topic echo /local_costmap/voxel_grid >> /topic_messages/_local_costmap_voxel_grid.txt &
ros2 topic echo /local_costmap/voxel_marked_cloud >> /topic_messages/_local_costmap_voxel_marked_cloud.txt &
ros2 topic echo /local_plan >> /topic_messages/_local_plan.txt &
ros2 topic echo /map >> /topic_messages/_map.txt &
ros2 topic echo /map_metadata >> /topic_messages/_map_metadata.txt &
ros2 topic echo /map_saver/transition_event >> /topic_messages/_map_saver_transition_event.txt &
ros2 topic echo /map_updates >> /topic_messages/_map_updates.txt &
ros2 topic echo /marker >> /topic_messages/_marker.txt &
ros2 topic echo /mobile_base/sensors/bumper_pointcloud >> /topic_messages/_mobile_base_sensors_bumper_pointcloud.txt &
ros2 topic echo /odom >> /topic_messages/_odom.txt &
ros2 topic echo /parameter_events >> /topic_messages/_parameter_events.txt &
ros2 topic echo /particle_cloud >> /topic_messages/_particle_cloud.txt &
ros2 topic echo /performance_metrics >> /topic_messages/_performance_metrics.txt &
ros2 topic echo /plan >> /topic_messages/_plan.txt &
ros2 topic echo /planner_server/transition_event >> /topic_messages/_planner_server_transition_event.txt &
ros2 topic echo /received_global_plan >> /topic_messages/_received_global_plan.txt &
ros2 topic echo /recoveries_server/transition_event >> /topic_messages/_recoveries_server_transition_event.txt &
ros2 topic echo /robot_description >> /topic_messages/_robot_description.txt &
ros2 topic echo /rosout >> /topic_messages/_rosout.txt &
ros2 topic echo /scan >> /topic_messages/_scan.txt &
ros2 topic echo /slam_toolbox/feedback >> /topic_messages/_slam_toolbox_feedback.txt &
ros2 topic echo /slam_toolbox/graph_visualization >> /topic_messages/_slam_toolbox_graph_visualization.txt &
ros2 topic echo /slam_toolbox/scan_visualization >> /topic_messages/_slam_toolbox_scan_visualization.txt &
ros2 topic echo /slam_toolbox/update >> /topic_messages/_slam_toolbox_update.txt &
ros2 topic echo /speed_limit >> /topic_messages/_speed_limit.txt &
ros2 topic echo /tf >> /topic_messages/_tf.txt &
ros2 topic echo /tf_static >> /topic_messages/_tf_static.txt &
ros2 topic echo /transformed_global_plan >> /topic_messages/_transformed_global_plan.txt &
ros2 topic echo /waypoint_follower/transition_event >> /topic_messages/_waypoint_follower_transition_event.txt &
ros2 topic echo /waypoints >> /topic_messages/_waypoints.txt &